spring:
  datasource:
    url: jdbc:db2://localhost:50000/INSDB
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    username: dree0313
    password: Dree0313

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.DB2Dialect
    show-sql: true
